services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  localstack:
    build: ./localstack-init
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - AWS_DEFAULT_REGION=us-east-2

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=formulus
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
