services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-2
    volumes:
      - ${PWD}/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=formulus
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
